spring.application.name=auth-service
server.port=${AUTH_SERVICE_PORT:8081}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/skybooker_auth_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

app.admin.secret-key=${ADMIN_SECRET_KEY}
app.staff.secret-key=${STAFF_SECRET_KEY}

google.client-id=${GOOGLE_CLIENT_ID}

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:false}

logging.file.name=logs/auth-service.log
logging.level.com.skybooker=${LOG_LEVEL:INFO}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
