spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/skybooker_auth_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret=my-super-secret-key-my-super-secret-key-12345
jwt.expiration=86400000

app.admin.secret-key=SkyAdmin#9999
app.staff.secret-key=SkyStaff#2025

# ?? PASTE YOUR GOOGLE CLIENT ID BELOW
# Get it from: console.cloud.google.com ? APIs & Services ? Credentials
# It looks like: 123456789-abcxyz.apps.googleusercontent.com
google.client-id=696364307002-vaeu51cudrft0sh0dimjacfkk71vf07u.apps.googleusercontent.com

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true


logging.file.name=logs/auth-service.log
logging.level.com.skybooker=INFO

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest