spring.application.name=notification-service
server.port=8088

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Gmail SMTP — replace with your Gmail + App Password
# To get App Password: Google Account -> Security -> 2-Step Verification -> App Passwords
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=skybooker.support@gmail.com
spring.mail.password=fbplmltwflknktjs

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Sender display name
app.mail.from=SkyBooker <skybooker.support@gmail.com>
