sonar.projectKey=Parv-Agrawal26_SkyBooker-Airline-Management-System
sonar.organization=parv-agrawal26
sonar.host.url=https://sonarcloud.io
sonar.projectName=SkyBooker Airline Management System

sonar.sources=auth-service/src/main,flight-booking/src/main,Flight-Service/src/main,Airline-Service/src/main,Notification-Service/src/main,Passenger-Service/src/main,Payment-Service/src/main,Seat-Service/src/main,api-gateway/src/main

sonar.tests=auth-service/src/test,flight-booking/src/test,Flight-Service/src/test,Airline-Service/src/test,Passenger-Service/src/test,Payment-Service/src/test,Seat-Service/src/test

sonar.java.binaries=auth-service/target/classes,flight-booking/target/classes,Flight-Service/target/classes,Airline-Service/target/classes,Notification-Service/target/classes,Passenger-Service/target/classes,Payment-Service/target/classes,Seat-Service/target/classes,api-gateway/target/classes

sonar.coverage.jacoco.xmlReportPaths=auth-service/target/site/jacoco/jacoco.xml,flight-booking/target/site/jacoco/jacoco.xml,Flight-Service/target/site/jacoco/jacoco.xml,Airline-Service/target/site/jacoco/jacoco.xml,Passenger-Service/target/site/jacoco/jacoco.xml,Payment-Service/target/site/jacoco/jacoco.xml,Seat-Service/target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/node_modules/**,**/*.class
